#!/bin/sh
# Helper to start Open Peer Power Core inside the devcontainer

# Stop on errors
set -e

if [ -z "${DEVCONTAINER}" ]; then
  echo "This task should only run inside a devcontainer, for local install OP Core in a venv."
  exit 1
fi

if [ -z $(which opp) ]; then
  echo "Installing Home Asstant core from dev."
  python3 -m pip install --upgrade \
    colorlog \
    git+git://github.com/open-peer-power/open-peer-power.git@dev
fi

if [ ! -d "/workspaces/frontend/config" ]; then
  echo "Creating default configuration."
  mkdir -p "/workspaces/frontend/config";
  opp --script ensure_config -c config
  echo "demo:

logger:
  default: info
  logs:
    openpeerpower.components.frontend: debug
" >> /workspaces/frontend/config/configuration.yaml

  if [ ! -z "${OPPIO}" ]; then
  echo "
# frontend:
#   development_repo: /workspaces/frontend

oppio:
  development_repo: /workspaces/frontend" >> /workspaces/frontend/config/configuration.yaml
  else
  echo "
frontend:
  development_repo: /workspaces/frontend

# oppio:
#   development_repo: /workspaces/frontend" >> /workspaces/frontend/config/configuration.yaml
  fi

fi

opp -c /workspaces/frontend/config
